---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
- name: Copy nginx conf
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  notify:
    - restart nginx
