apiVersion: apps/v1
kind: Deployment 
metadata:
  name: captain-deployment
  labels: 
    app: captain-clapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: captain-clapp
  template:
    metadata:
      labels:
        app: captain-clapp 
    spec:
      containers:
      - name: k8s-demo
        image: vinga2805/mynodejsapp 
        ports:
        - name: nodejs-port
          containerPort: 3000
